// Code generated by MockGen. DO NOT EDIT.
// Source: adapter/llm_adapter.go
//
// Generated by this command:
//
//	mockgen -source=adapter/llm_adapter.go -destination=tests/mock/llm_adapter_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	adapter "github.com/hackathon-20260110/api/adapter"
	gomock "go.uber.org/mock/gomock"
	genai "google.golang.org/genai"
)

// MockLLMAdapter is a mock of LLMAdapter interface.
type MockLLMAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockLLMAdapterMockRecorder
	isgomock struct{}
}

// MockLLMAdapterMockRecorder is the mock recorder for MockLLMAdapter.
type MockLLMAdapterMockRecorder struct {
	mock *MockLLMAdapter
}

// NewMockLLMAdapter creates a new mock instance.
func NewMockLLMAdapter(ctrl *gomock.Controller) *MockLLMAdapter {
	mock := &MockLLMAdapter{ctrl: ctrl}
	mock.recorder = &MockLLMAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMAdapter) EXPECT() *MockLLMAdapterMockRecorder {
	return m.recorder
}

// CreateChatCompletion mocks base method.
func (m *MockLLMAdapter) CreateChatCompletion(contents []*genai.Content, model adapter.LLMModelType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletion", contents, model)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletion indicates an expected call of CreateChatCompletion.
func (mr *MockLLMAdapterMockRecorder) CreateChatCompletion(contents, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletion", reflect.TypeOf((*MockLLMAdapter)(nil).CreateChatCompletion), contents, model)
}

// CreateChatCompletionJSON mocks base method.
func (m *MockLLMAdapter) CreateChatCompletionJSON(contents []*genai.Content, model adapter.LLMModelType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletionJSON", contents, model)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletionJSON indicates an expected call of CreateChatCompletionJSON.
func (mr *MockLLMAdapterMockRecorder) CreateChatCompletionJSON(contents, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletionJSON", reflect.TypeOf((*MockLLMAdapter)(nil).CreateChatCompletionJSON), contents, model)
}
