// Code generated by MockGen. DO NOT EDIT.
// Source: adapter/r2_adapter.go
//
// Generated by this command:
//
//	mockgen -source=adapter/r2_adapter.go -destination=tests/mock/r2_adapter_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockR2Adapter is a mock of R2Adapter interface.
type MockR2Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockR2AdapterMockRecorder
	isgomock struct{}
}

// MockR2AdapterMockRecorder is the mock recorder for MockR2Adapter.
type MockR2AdapterMockRecorder struct {
	mock *MockR2Adapter
}

// NewMockR2Adapter creates a new mock instance.
func NewMockR2Adapter(ctrl *gomock.Controller) *MockR2Adapter {
	mock := &MockR2Adapter{ctrl: ctrl}
	mock.recorder = &MockR2AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockR2Adapter) EXPECT() *MockR2AdapterMockRecorder {
	return m.recorder
}

// UploadImage mocks base method.
func (m *MockR2Adapter) UploadImage(image []byte, path, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", image, path, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockR2AdapterMockRecorder) UploadImage(image, path, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockR2Adapter)(nil).UploadImage), image, path, contentType)
}
